[general]
database_url = "sqlite:///./f1_predictions.db"

[theme]
primaryColor = "#FF1801"  # F1 Red
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 